const totalSongs = [
    {
        songName: "",
        artistsName: "",
        songCover: "",
        songDuration: "",
        isLiked: "",
    },
    {
        songName: "",
        artistsName: "",
        songCover: "",
        songDuration: "",
        isLiked: "",
    },
    {
        songName: "",
        artistsName: "",
        songCover: "",
        songDuration: "",
        isLiked: "",
    },
    {
        songName: "",
        artistsName: "",
        songCover: "",
        songDuration: "",
        isLiked: "",
    },
    {
        songName: "",
        artistsName: "",
        songCover: "",
        songDuration: "",
        isLiked: "",
    },
    {
        songName: "",
        artistsName: "",
        songCover: "",
        songDuration: "",
        isLiked: "",
    },
    {
        songName: "",
        artistsName: "",
        songCover: "",
        songDuration: "",
        isLiked: "",
    },
    {
        songName: "",
        artistsName: "",
        songCover: "",
        songDuration: "",
        isLiked: "",
    },
    {
        songName: "",
        artistsName: "",
        songCover: "",
        songDuration: "",
        isLiked: "",
    },
    {
        songName: "",
        artistsName: "",
        songCover: "",
        songDuration: "",
        isLiked: "",
    },
    {
        songName: "",
        artistsName: "",
        songCover: "",
        songDuration: "",
        isLiked: "",
    },
    {
        songName: "",
        artistsName: "",
        songCover: "",
        songDuration: "",
        isLiked: "",
    },
    {
        songName: "",
        artistsName: "",
        songCover: "",
        songDuration: "",
        isLiked: "",
    },
    {
        songName: "",
        artistsName: "",
        songCover: "",
        songDuration: "",
        isLiked: "",
    },
    {
        songName: "",
        artistsName: "",
        songCover: "",
        songDuration: "",
        isLiked: "",
    },
    {
        songName: "",
        artistsName: "",
        songCover: "",
        songDuration: "",
        isLiked: "",
    },
]